export const MaskString = '***';

export const OTPApiCode = {
  MaxOTPRequest: 'MAX_OTP_REQUESTS_REACHED',
};

export const FILE_TYPE_VALUE = {
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
  BUSINESS_REGULATIONS: 'BUSINESS_REGULATIONS',
  DIRECTOR_APPOINTMENT: 'DIRECTOR_APPOINTMENT',
  REPRESENTATIVE_DOCUMENT: 'REPRESENTATIVE_DOCUMENT',
  CHIEF_ACCOUNTANT_APPOINTMENT: 'CHIEF_ACCOUNTANT_APPOINTMENT',
  BENEFIT_OWNER_DOCUMENT: 'BENEFIT_OWNER_DOCUMENT',
  FOUND_DOCUMENT: 'FOUND_DOCUMENT',
};

export const CIC_TYPE_VALUE = {
  PERSON_IDCARD_FRONT: 'PERSON_IDCARD_FRONT',
  PERSON_IDCARD_BACK: 'PERSON_IDCARD_BACK',
};

export const PERSON_TITLE_TYPE = {
  DIRECTOR: 'DIRECTOR',
  ACCOUNTANT: 'ACCOUNTANT',
  LAW_REPRESENTATIVE: 'LAW_REPRESENTATIVE',
  BENEFICIAL_OWNER: 'BENEFICIAL_OWNER',
  FOUNDER: 'FOUNDER',
};

export const IMAGE_FILE_TYPE = ['image/png', 'image/jpeg'];

export const PDF_FILE_TYPE = ['application/pdf'];
export const ONE_MONTH = 2630000;
export const FIVE_YEARS = 157680000;
